- name: Install packages
  tags: package
  yum:  name={{ item }} state=latest
  with_items:
    - hadoop-hdfs-datanode

- name: Destroy data
  tags: init
  command: rm -rf {{ item }}
  with_items: "{{ dfs_datanode_data_dir.replace('file://','').split(',') }}"
  when: destroy_data

- name: Create datanode directories
  file: dest={{ item }} owner={{ hadoop_user }} group={{ hadoop_user }} state=directory
  with_items: "{{ dfs_datanode_data_dir.replace('file://','').split(',') }}"

- name: Install default configurations
  tags: config
  template: src=default/{{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - hadoop-hdfs-datanode

- name: Start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - hadoop-hdfs-datanode
