- include: base.yml
  when: deploy == "base"

- include: namenode.yml
  when: deploy == "namenodes"

- include: datanode.yml
  when: deploy == "datanodes"

- include: test_hdfs.yml
  when: deploy == "test_hdfs"
