---
- hosts: all
  roles:
    - common

- hosts: all
  roles:
    - { role: hadoop, deploy: 'base' }

- name: Deploy namenodes
  tags: namenodes
  hosts: namenodes
  roles:
    - { role: hadoop, deploy: 'namenodes' }

- name: Deploy datanodes
  tags: datanodes
  hosts: datanodes
  roles:
    - { role: hadoop, deploy: 'datanodes' }

- name: Test hdfs
  tags: test
  hosts: namenodes
  roles:
    - { role: hadoop, deploy: 'test_hdfs' }

- name: Deploy yarn resource manager
  tags: yarnresourcemanager
  hosts: yarnresourcemanager
  roles:
    - { role: hadoop, deploy: 'resourcemanager' }

- name: Test mapreduce
  tags: test
  hosts: yarnresourcemanager
  roles:
    - { role: hadoop, deploy: 'test_mapreduce' }
