---
- hosts: all
  roles:
    - common

- hosts: all
  roles:
    - { role: hadoop, deploy: 'base' }

- name: Deploy zookeeper
  hosts: zookeepernodes
  tags: zookeepernodes
  roles:
    - zookeeper

- name: Deploy namenodes
  tags: namenodes
  hosts: namenodes
  roles:
    - { role: hadoop, deploy: 'namenodes' }

- name: Deploy yarn resource manager
  tags: yarnresourcemanager
  hosts: yarnresourcemanager
  roles:
    - { role: hadoop, deploy: 'resourcemanager' }

- name: Deploy datanodes
  tags: datanodes
  hosts: datanodes
  roles:
    - { role: hadoop, deploy: 'datanodes' }

- name: Test hdfs
  tags: test
  hosts: namenodes
  roles:
    - { role: hadoop, deploy: 'test_hdfs' }

- name: Test mapreduce
  tags: test
  hosts: yarnresourcemanager
  roles:
    - { role: hadoop, deploy: 'test_mapreduce' }

- name: Deploy kafka
  tags: kafka
  hosts: kafka
  roles:
    - { role: kafka, deploy: 'install' }
    - { role: kafka, deploy: 'test_kafka' }
