---
# tasks file for common
- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_eth0.ipv4.address }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].ansible_hostname }}"
    state: present
  with_items: "{{ groups.all }}"

- name: Adding of Cloudera repository
  get_url:
    url: http://archive.cloudera.com/cdh4/redhat/6/x86_64/cdh/cloudera-cdh4.repo
    dest: /etc/yum.repos.d/cdh-4.repo

- name: Adding of Bigtop repository
  get_url:
    url: http://www.apache.org/dist/bigtop/bigtop-1.2.0/repos/centos6/bigtop.repo
    dest: /etc/yum.repos.d/bigtop.repo

- name: Adding of Bigtop GPG keys
  get_url:
    url: https://dist.apache.org/repos/dist/release/bigtop/KEYS
    dest: /etc/pki/rpm-gpg/Bigtop

- name: Installing of basic packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - java-1.8.0
    - bigtop-utils
    - redhat-lsb-core
    - hadoop-mapreduce

- name: Install template configurations
  tags: config
  template: src={{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - bigtop-utils

- name: Create directories
  tags: config
  file: path="{{ item | regex_replace('[^/]+/*$','') }}" state=directory owner=root group=root mode=755 follow=yes
  with_items:
    - "{{ zookeeper_data_dir }}"
    - "{{ log_folder }}"
    - "{{ etc_folder }}"

- name: Creating of hadoop users
  user:
   name: "{{ item }}"
   generate_ssh_key: yes
   group: hadoop
  with_items:
    - "{{ hadoop_user }}"
    - "{{ yarn_user }}"
    - "{{ mapred_user }}"

- name: Collect public keys form hosts
  fetch:
    src: /home/{{ hadoop_user }}/.ssh/id_rsa.pub
    dest: "{{ playbook_dir }}/public_keys"

- name: Adding of public keys from servers for hadoop user
  authorized_key:
    user: "{{ hadoop_user }}"
    state: present
    key: "{{ lookup('file', playbook_dir + '/public_keys/' + item + '/home/' + hadoop_user + '/.ssh/id_rsa.pub') }}"
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname != item

- name: Adding of local public key for users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  with_items:
    - centos
    - "{{ hadoop_user }}"
