---
# tasks file for common
- name: Installing of basic packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.8.0-openjdk

- name: Creating of hadoop-user
  user:
   name: hadoop
   password: "$6$Ttit1ZVLkrC0b/o6$qd5Hvffh5yIxd38bkQFIOFrgxw/PHIWRtrXkb5XZXer6rYuCE7O8nglYQxWXYMWOKzJLC87v6q0GA1v7zbYqa."
   generate_ssh_key: yes

- name: Allow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication yes"
              state=present
  notify: Restart ssh

- name: ensure private key and public one are present
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/hadoop/.ssh/{{ item }}"
    mode: 0600
  with_items:
    - id_rsa.pub
    - id_rsa

- name: Adding of public keys for hadoop user
  authorized_key:
    user: hadoop
    state: present
    key: "{{ lookup('file', role_path + '/files/id_rsa.pub') }}"
