---
# tasks file for common
- name: Installing of basic packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.8.0-openjdk

- name: Creating of hadoop-user
  user:
   name: "{{ hadoop_user }}"
   generate_ssh_key: yes

- name: Collect public keys form hosts
  fetch:
    src: /home/{{ hadoop_user }}/.ssh/id_rsa.pub
    dest: "{{ playbook_dir }}/public_keys"

- name: Adding of public keys from servers for hadoop user
  authorized_key:
    user: "{{ hadoop_user }}"
    state: present
    key: "{{ lookup('file', playbook_dir + '/public_keys/' + item + '/home/' + hadoop_user + '/.ssh/id_rsa.pub') }}"
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname != item

- name: Adding of local public key for users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  with_items:
    - cenots
    - vagrant
    - "{{ hadoop_user }}"
